#! /usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np

data1 = np.loadtxt("data/Q6.1_E_T-3.9_init_1.dat")
data2 = np.loadtxt("data/Q6.1_E_T-3.9_init_m1.dat")
data3 = np.loadtxt("data/Q6.1_E_T-3.9_init_rand.dat")
data4 = np.loadtxt("data/Q6.1_M_T-3.9_init_1.dat")
data5 = np.loadtxt("data/Q6.1_M_T-3.9_init_m1.dat")
data6 = np.loadtxt("data/Q6.1_M_T-3.9_init_rand.dat")
data7 = np.loadtxt("data/Q6.2_E_T-3.9_init_1.dat")
data8 = np.loadtxt("data/Q6.2_E_T-3.9_init_m1.dat")
data9 = np.loadtxt("data/Q6.2_E_T-3.9_init_rand.dat")
data10 = np.loadtxt("data/Q6.2_M_T-3.9_init_1.dat")
data11 = np.loadtxt("data/Q6.2_M_T-3.9_init_m1.dat")
data12 = np.loadtxt("data/Q6.2_M_T-3.9_init_rand.dat")
data13 = np.loadtxt("data/Q6.3_E_T-3.9_init_1.dat")
data14 = np.loadtxt("data/Q6.3_E_T-3.9_init_m1.dat")
data15 = np.loadtxt("data/Q6.3_E_T-3.9_init_rand.dat")
data16 = np.loadtxt("data/Q6.3_M_T-3.9_init_1.dat")
data17 = np.loadtxt("data/Q6.3_M_T-3.9_init_m1.dat")
data18 = np.loadtxt("data/Q6.3_M_T-3.9_init_rand.dat")
x = np.linspace(0,len(data1), len(data1)).astype(int)

plt.plot(x, data1, label="L: 8; Init: +1")
plt.plot(x, data2, label="L: 8; Init: -1")
plt.plot(x, data3, label="L: 8; Init: random")
plt.plot(x, data7, label="L: 9; Init: +1")
plt.plot(x, data8, label="L: 9; Init: -1")
plt.plot(x, data9, label="L: 9; Init: random")
plt.plot(x, data13, label="L: 10; Init: +1")
plt.plot(x, data14, label="L: 10; Init: -1")
plt.plot(x, data15, label="L: 10; Init: random")
plt.xlabel("Iterations")
plt.ylabel("Energy per spin")
plt.title("Energy per Spin : k$_B$T = 3.9")
ax = plt.gca()
ax.set_ylim([-3, 0])
plt.legend()
plt.savefig("figures/Q6_Energy.png")

plt.clf()

plt.plot(x, data4, label="L: 8; Init: +1")
plt.plot(x, data5, label="L: 8; Init: -1")
plt.plot(x, data6, label="L: 8; Init: random")
plt.plot(x, data10, label="L: 9; Init: +1")
plt.plot(x, data11, label="L: 9; Init: -1")
plt.plot(x, data12, label="L: 9; Init: random")
plt.plot(x, data16, label="L: 10; Init: +1")
plt.plot(x, data17, label="L: 10; Init: -1")
plt.plot(x, data18, label="L: 10; Init: random")
plt.xlabel("Iterations")
plt.ylabel("Magnetization per spin")
plt.title("Magnetization per Spin : k$_B$T = 3.9")
ax = plt.gca()
ax.set_ylim([-1, 1])
plt.legend()
plt.savefig("figures/Q6_Magnetization.png")
